### ISSUE TITLE
⚒️[FEATURE]: QuickNode Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#49]
## Describe the feature you'd like
QuickNode integration
Docs: https://www.quicknode.com/docs

## ✅Tasks
- [ ] Add QuickNode and QuickNodeTrigger as new nodes.
- [ ] Add QuickNode as new network provider.

## 🎯Acceptance Criteria
- [ ] QuickNode and QuickNodeTrigger nodes should have majority of the APIs from the docs implemented.
- [ ] QuickNode credential will be available as one of the network provider options.

## More info
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾
