### ISSUE TITLE
⚒️[FEATURE] Magic Eden (Solana) Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#55]
## Describe the feature you'd like
Magic Eden (Solana) Integration
Docs: https://api.magiceden.dev/

## ✅Tasks
- [ ] Add Magic Eden Action node.
- [ ] Add Magic Eden Trigger node.

## 🎯Acceptance Criteria
- [ ] Magic Eden action node should have some key APIs from the docs implemented.
- [ ] Magic Eden trigger node should have some key events from the docs implemented, such as new sales, new transfer etc.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)
 - Similar nodes to refer - [OpenSea](https://github.com/Outerbridgeio/Outerbridge/tree/master/packages/components/nodes/Opensea)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾
