### ISSUE TITLE
⚒️[FEATURE] FTX Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#72]
## Describe the feature you'd like
FTX Integration
Docs: https://docs.ftx.com/#overview

## ✅Tasks
- [ ] Add FTX action node.
- [ ] Add FTX webhook node.

## 🎯Acceptance Criteria
- [ ] FTX action node should have some key APIs from the docs implemented such as send, receive, buy, sell, deposit, withdraw.
- [ ] FTX webhook node should have events from the [docs](https://docs.ftx.com/#websocket-api) implemented

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)
 - Similar action node - [Binance](https://github.com/Outerbridgeio/Outerbridge/tree/master/packages/components/nodes/Binance)
 - Similar webhook node - [Alchemy Webhook](https://github.com/Outerbridgeio/Outerbridge/blob/master/packages/components/nodes/Alchemy/AlchemyWebhook.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾
